### ISSUE TITLE
节点数超过500个就无法再加了

### ISSUE THREAD

**Issue by HeYuqiu** [wzshiming/fake-kubelet#38]
问题现象：按照yaml：https://raw.githubusercontent.com/wzshiming/fake-kubelet/master/deploy.yaml  部署
默认5个节点，部署成功，将节点数改为500（修改fake-kubelet deployment 将 GENERATE_REPLICAS=500），500节点成功生成。
但是再将节点数改为510，就无法生成节点了，fake-kubelet pod 开始crash，报错信息如下：

[fake-kubelet] 2022/06/09 12:02:38 Lock node fake-259
[fake-kubelet] 2022/06/09 12:02:38 Lock node fake-261
[fake-kubelet] 2022/06/09 12:02:38 Lock node fake-263
[fake-kubelet] 2022/06/09 12:02:38 Lock node fake-264
[fake-kubelet] 2022/06/09 12:02:38 Lock node fake-262
[fake-kubelet] 2022/06/09 12:02:38 Lock node fake-265
[fake-kubelet] 2022/06/09 12:02:38 Lock node fake-266
[fake-kubelet] 2022/06/09 12:02:38 Skip pod kube-proxy-pnlp2.kube-system on fake-251: do not need to modify
[fake-kubelet] 2022/06/09 12:02:38 Lock pod kube-proxy-pnlp2.kube-system on fake-251
[fake-kubelet] 2022/06/09 12:02:38 Skip pod kube-flannel-ds-wc2jk.kube-system on fake-251: do not need to modify
[fake-kubelet] 2022/06/09 12:02:38 Lock pod kube-flannel-ds-wc2jk.kube-system on fake-251
[fake-kubelet] 2022/06/09 12:02:38 Skip pod prometheus-stack-node-exporter-8kgq5.monitoring on fake-251: do not need to modify
[fake-kubelet] 2022/06/09 12:02:38 Lock pod prometheus-stack-node-exporter-8kgq5.monitoring on fake-251
[fake-kubelet] 2022/06/09 12:02:39 Failed to lock node fake-267: Get "https://172.25.160.1:443/api/v1/nodes/fake-267": context canceled
[fake-kubelet] 2022/06/09 12:02:39 Failed to lock node fake-268: context canceled
[fake-kubelet] 2022/06/09 12:02:39 Failed to lock node fake-269: context canceled
[fake-kubelet] 2022/06/09 12:02:39 Stop watch pods
[fake-kubelet] 2022/06/09 12:02:39 Stop keep nodes heartbeat
[fake-kubelet] 2022/06/09 12:02:39 failed to start nodes controller: context canceled

**Comment by wzshiming** [comment]
改了 GENERATE_REPLICAS 之后 将会重新创建 fake-kubelet Pod, 旧的 Pod 是退出状态, 所以将会看到退出的日志
等待新的 Pod 启动完毕接管之前创建的 Node 之后, 会继续创建新的的 Node

**Comment by wzshiming** [comment]
我试了下新的 Pod 由于长时间没 Ready 导致被 Kubelet kill 了, 旧的 Pod 又不再接管了, 导致这个问题

**Comment by wzshiming** [comment]
临时避免方案
主动 delete 掉旧的 fake-kubelet 的 pod

后续版本我将修复这个问题

**Comment by wzshiming** [comment]
在新版本已经修复了, 如果有时间的话可以再试一下

**Comment by HeYuqiu** [comment]
> 在新版本已经修复了, 如果有时间的话可以再试一下

已验证，问题已经修复了，感谢！
