### ISSUE TITLE
fake-kubelet for kubelet api compatibility test?

### ISSUE THREAD

**Issue by alexzhc** [wzshiming/fake-kubelet#49]
hi, @wzshiming, 

I'd like to use fake-kubelet for kube api compatibility test? Is there a specific kube version for each release ?

Thanks

**Comment by wzshiming** [comment]
fake-kubelet only minimally maintains Node and Pod, and doesn't care about the kube version.

I guess you need this https://github.com/wzshiming/fake-k8s can meet your requirements for kube API compatibility testing

**Comment by wzshiming** [comment]
Moved to https://github.com/kubernetes-sigs/kwok
Close this
